"use client";

import { FormEvent, useState } from "react";
import { useLanguage } from "@/components/LanguageProvider";

const data = {
  sk:{kicker:"NEZÁVÄZNÝ DOPYT",title:"Získajte cenovú ponuku na mieru",intro:"Vyplňte základné informácie. Čím presnejšie zadanie, tým presnejšie viem pripraviť rozsah, technológiu a cenu.",name:"Meno a priezvisko *",company:"Firma / organizácia",email:"E-mail *",phone:"Telefón",need:"Čo potrebujete vytvoriť?",budget:"Orientačný rozpočet",deadline:"Požadovaný termín",detail:"Detail zadania *",namePh:"Vaše meno",companyPh:"Názov spoločnosti",deadlinePh:"napr. do 30 dní / dohodou",detailPh:"Popíšte cieľ projektu, hlavné funkcie, používateľov, potrebné napojenia/API, existujúce systémy a prípadné technologické preferencie.",benefits:["návrh vhodnej technológie","individuálne nacenenie","odpoveď obratom do e-mailu"],legal:"Odoslaním nevzniká objednávka ani záväzok. Údaje slúžia výhradne na spracovanie dopytu a prípravu cenovej ponuky.",button:"Požiadať o cenovú ponuku",missing:"Vyplňte, prosím, meno, e-mail a popis požiadavky.",opening:"Dopyt je pripravený. Otváram e-mailovú aplikáciu…",subject:"Žiadosť o cenovú ponuku",hello:"Dobrý deň,\n\nžiadam o prípravu cenovej ponuky na mieru.",request:"Prosím o návrh riešenia a cenovú ponuku na mieru."},
  cs:{kicker:"NEZÁVAZNÁ POPTÁVKA",title:"Získejte cenovou nabídku na míru",intro:"Vyplňte základní informace. Čím přesnější zadání, tím přesněji lze připravit rozsah, technologii a cenu.",name:"Jméno a příjmení *",company:"Firma / organizace",email:"E-mail *",phone:"Telefon",need:"Co potřebujete vytvořit?",budget:"Orientační rozpočet",deadline:"Požadovaný termín",detail:"Detail zadání *",namePh:"Vaše jméno",companyPh:"Název společnosti",deadlinePh:"např. do 30 dnů / dohodou",detailPh:"Popište cíl projektu, hlavní funkce, uživatele, potřebná napojení/API, stávající systémy a technologické preference.",benefits:["návrh vhodné technologie","individuální nacenění","rychlá odpověď e-mailem"],legal:"Odesláním nevzniká objednávka ani závazek. Údaje slouží pouze ke zpracování poptávky a přípravě nabídky.",button:"Požádat o cenovou nabídku",missing:"Vyplňte prosím jméno, e-mail a popis požadavku.",opening:"Poptávka je připravena. Otevírám e-mailovou aplikaci…",subject:"Žádost o cenovou nabídku",hello:"Dobrý den,\n\nžádám o přípravu cenové nabídky na míru.",request:"Prosím o návrh řešení a cenovou nabídku na míru."},
  en:{kicker:"NO-OBLIGATION ENQUIRY",title:"Get a tailored quote",intro:"Share the essentials. The more precise the brief, the more accurately I can define scope, technology and price.",name:"Full name *",company:"Company / organisation",email:"E-mail *",phone:"Phone",need:"What do you need built?",budget:"Indicative budget",deadline:"Target deadline",detail:"Project brief *",namePh:"Your name",companyPh:"Company name",deadlinePh:"e.g. within 30 days / flexible",detailPh:"Describe the goal, key features, users, integrations/APIs, existing systems and any technology preferences.",benefits:["technology recommendation","individual pricing","fast response by e-mail"],legal:"Submitting this form does not create an order or obligation. Your data is used only to process the enquiry and prepare a quotation.",button:"Request a quote",missing:"Please enter your name, e-mail and project description.",opening:"Your enquiry is ready. Opening your e-mail app…",subject:"Request for quotation",hello:"Hello,\n\nI would like to request a tailored quotation.",request:"Please send me a proposed solution and a tailored quotation."},
  de:{kicker:"UNVERBINDLICHE ANFRAGE",title:"Individuelles Angebot erhalten",intro:"Teilen Sie die wichtigsten Informationen. Je genauer das Briefing, desto präziser lassen sich Umfang, Technologie und Preis bestimmen.",name:"Vor- und Nachname *",company:"Unternehmen / Organisation",email:"E-Mail *",phone:"Telefon",need:"Was soll entwickelt werden?",budget:"Orientierungsbudget",deadline:"Gewünschter Termin",detail:"Projektbeschreibung *",namePh:"Ihr Name",companyPh:"Unternehmensname",deadlinePh:"z. B. innerhalb von 30 Tagen / flexibel",detailPh:"Beschreiben Sie Ziel, Funktionen, Nutzer, Integrationen/APIs, bestehende Systeme und technologische Präferenzen.",benefits:["passende Technologieempfehlung","individuelle Kalkulation","schnelle Antwort per E-Mail"],legal:"Mit dem Absenden entsteht weder eine Bestellung noch eine Verpflichtung. Die Daten werden ausschließlich zur Bearbeitung der Anfrage verwendet.",button:"Angebot anfordern",missing:"Bitte Name, E-Mail und Projektbeschreibung ausfüllen.",opening:"Ihre Anfrage ist vorbereitet. E-Mail-App wird geöffnet…",subject:"Anfrage für ein Angebot",hello:"Guten Tag,\n\nich bitte um ein individuelles Angebot.",request:"Bitte senden Sie mir einen Lösungsvorschlag und ein individuelles Angebot."},
  pl:{kicker:"NIEZOBOWIĄZUJĄCE ZAPYTANIE",title:"Otrzymaj wycenę dopasowaną do projektu",intro:"Podaj podstawowe informacje. Im dokładniejszy brief, tym precyzyjniej można określić zakres, technologię i cenę.",name:"Imię i nazwisko *",company:"Firma / organizacja",email:"E-mail *",phone:"Telefon",need:"Co chcesz stworzyć?",budget:"Orientacyjny budżet",deadline:"Oczekiwany termin",detail:"Opis projektu *",namePh:"Twoje imię i nazwisko",companyPh:"Nazwa firmy",deadlinePh:"np. do 30 dni / do ustalenia",detailPh:"Opisz cel projektu, kluczowe funkcje, użytkowników, integracje/API, obecne systemy i preferowane technologie.",benefits:["dobór odpowiedniej technologii","indywidualna wycena","szybka odpowiedź e-mailem"],legal:"Wysłanie formularza nie stanowi zamówienia ani zobowiązania. Dane służą wyłącznie do obsługi zapytania i przygotowania wyceny.",button:"Poproś o wycenę",missing:"Uzupełnij imię, e-mail i opis projektu.",opening:"Zapytanie jest gotowe. Otwieram aplikację e-mail…",subject:"Prośba o wycenę",hello:"Dzień dobry,\n\nproszę o przygotowanie indywidualnej wyceny.",request:"Proszę o propozycję rozwiązania i wycenę dopasowaną do projektu."},
  es:{kicker:"SOLICITUD SIN COMPROMISO",title:"Obtenga un presupuesto a medida",intro:"Comparta la información básica. Cuanto más preciso sea el briefing, más exactos podrán ser el alcance, la tecnología y el precio.",name:"Nombre completo *",company:"Empresa / organización",email:"E-mail *",phone:"Teléfono",need:"¿Qué necesita desarrollar?",budget:"Presupuesto orientativo",deadline:"Plazo deseado",detail:"Descripción del proyecto *",namePh:"Su nombre",companyPh:"Nombre de la empresa",deadlinePh:"p. ej. en 30 días / flexible",detailPh:"Describa el objetivo, funciones principales, usuarios, integraciones/API, sistemas existentes y preferencias tecnológicas.",benefits:["recomendación tecnológica","precio personalizado","respuesta rápida por e-mail"],legal:"El envío del formulario no crea un pedido ni una obligación. Los datos se utilizan únicamente para procesar la solicitud y preparar el presupuesto.",button:"Solicitar presupuesto",missing:"Complete su nombre, e-mail y descripción del proyecto.",opening:"La solicitud está lista. Abriendo su aplicación de e-mail…",subject:"Solicitud de presupuesto",hello:"Hola,\n\nsolicito un presupuesto personalizado.",request:"Por favor, envíeme una propuesta de solución y un presupuesto a medida."}
};

const services=["Web / corporate website","E-shop / customer portal","Web application / internal system","AI chatbot / conversational bot","Custom AI agent / multi-agent solution","Standalone AI module / AI integration","Process automation / workflow","API / backend / integrations","Python development / scripts / data processing","Kotlin / Android application","Flutter / Android / iOS application","Power BI / reporting / dashboards","Excel / Power Query / VBA automation","Tableau / visualisations","SQL / Microsoft SQL Server / databases","Oracle / PL/SQL","Other programming language / custom development","End-to-end solution from design to deployment"];
const budgets=["Need a quote","Up to €500","€500 – €1,500","€1,500 – €3,000","€3,000 – €5,000","€5,000 – €10,000","€10,000+"];

export default function ContactForm(){
 const {lang}=useLanguage(); const t=data[lang]; const [status,setStatus]=useState("");
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const value=(k:string)=>String(form.get(k)||"").trim();const name=value("name"),company=value("company"),email=value("email"),phone=value("phone"),service=value("service"),budget=value("budget"),deadline=value("deadline"),message=value("message");if(!name||!email||!message){setStatus(t.missing);return;}const subject=encodeURIComponent(`${t.subject} – ${service||"IT / AI"}`);const body=encodeURIComponent(`${t.hello}\n\nName: ${name}\nCompany: ${company||"–"}\nE-mail: ${email}\nPhone: ${phone||"–"}\nSolution: ${service||"–"}\nBudget: ${budget||"–"}\nDeadline: ${deadline||"–"}\n\nProject brief:\n${message}\n\n${t.request}`);setStatus(t.opening);window.location.href=`mailto:tutka.peter@gmail.com?subject=${subject}&body=${body}`}
 return <form className="contact-form" onSubmit={submit}>
  <div className="form-heading"><span>{t.kicker}</span><h3>{t.title}</h3><p>{t.intro}</p></div>
  <div className="field-row"><label><span>{t.name}</span><input name="name" autoComplete="name" placeholder={t.namePh} required/></label><label><span>{t.company}</span><input name="company" autoComplete="organization" placeholder={t.companyPh}/></label></div>
  <div className="field-row"><label><span>{t.email}</span><input name="email" type="email" autoComplete="email" placeholder="name@example.com" required/></label><label><span>{t.phone}</span><input name="phone" autoComplete="tel" placeholder="+421 ..."/></label></div>
  <label><span>{t.need}</span><select name="service" defaultValue={services[0]}>{services.map(s=><option key={s}>{s}</option>)}</select></label>
  <div className="field-row"><label><span>{t.budget}</span><select name="budget" defaultValue={budgets[0]}>{budgets.map(b=><option key={b}>{b}</option>)}</select></label><label><span>{t.deadline}</span><input name="deadline" placeholder={t.deadlinePh}/></label></div>
  <label><span>{t.detail}</span><textarea name="message" rows={7} placeholder={t.detailPh} required/></label>
  <div className="form-benefits" aria-label="Benefits">{t.benefits.map(x=><span key={x}>✓ {x}</span>)}</div>
  <div className="form-footer"><p>{t.legal}</p><button className="button button-primary" type="submit">{t.button} <span aria-hidden="true">→</span></button></div>{status&&<p className="form-status" role="status">{status}</p>}
 </form>
}
