"use client";

import { useLanguage } from "@/components/LanguageProvider";

const legal:any={
 sk:{back:"Späť na tutka.sk",title:"Ochrana osobných údajov",intro:"Táto stránka poskytuje základné informácie o spracovaní osobných údajov pri kontakte cez tutka.sk.",sections:[["Účel spracovania","Údaje uvedené pri dopyte sa používajú výlučne na komunikáciu o požadovanej službe, prípravu cenovej ponuky a následnú obchodnú komunikáciu."],["Rozsah údajov","Môže ísť najmä o meno, názov spoločnosti, e-mail, telefón a obsah požiadavky, ktoré používateľ uvedie dobrovoľne."],["Kontaktný formulár","Aktuálna verzia formulára pripraví správu v e-mailovom klientovi používateľa. Web samotný obsah formulára neukladá do databázy."],["Cookies a analytika","V základnej verzii nie sú integrované marketingové ani analytické cookies. Pri ich doplnení bude potrebné upraviť aj cookie režim."],["Kontakt","Kontaktný e-mail: tutka.peter@gmail.com"]]},
 cs:{back:"Zpět na tutka.sk",title:"Ochrana osobních údajů",intro:"Tato stránka poskytuje základní informace o zpracování osobních údajů při kontaktu přes tutka.sk.",sections:[["Účel zpracování","Údaje z poptávky se používají pouze pro komunikaci o požadované službě, přípravu cenové nabídky a následnou obchodní komunikaci."],["Rozsah údajů","Může jít zejména o jméno, název společnosti, e-mail, telefon a obsah požadavku uvedený dobrovolně."],["Kontaktní formulář","Aktuální formulář připraví zprávu v e-mailovém klientovi uživatele. Web obsah formuláře neukládá do databáze."],["Cookies a analytika","V základní verzi nejsou integrovány marketingové ani analytické cookies."],["Kontakt","Kontaktní e-mail: tutka.peter@gmail.com"]]},
 en:{back:"Back to tutka.sk",title:"Privacy policy",intro:"This page provides basic information about personal data processing when contacting TUTKA through tutka.sk.",sections:[["Purpose of processing","Information submitted with an enquiry is used solely to communicate about the requested service, prepare a quotation and continue relevant business communication."],["Data scope","This may include name, company, e-mail, phone number and the project description voluntarily provided by the user."],["Contact form","The current form prepares a message in the user's e-mail client. The website itself does not store the form content in a database."],["Cookies and analytics","The base version does not include marketing or analytics cookies. If such tools are added, this notice and cookie settings should be updated."],["Contact","Contact e-mail: tutka.peter@gmail.com"]]},
 de:{back:"Zurück zu tutka.sk",title:"Datenschutz",intro:"Diese Seite enthält grundlegende Informationen zur Verarbeitung personenbezogener Daten bei einer Kontaktaufnahme über tutka.sk.",sections:[["Zweck der Verarbeitung","Daten aus einer Anfrage werden ausschließlich zur Kommunikation über die gewünschte Leistung, zur Angebotserstellung und zur weiteren geschäftlichen Kommunikation verwendet."],["Umfang der Daten","Dazu können Name, Unternehmen, E-Mail, Telefonnummer und die freiwillig übermittelte Projektbeschreibung gehören."],["Kontaktformular","Das aktuelle Formular erstellt eine Nachricht im E-Mail-Programm des Nutzers. Die Website speichert die Formulardaten nicht in einer Datenbank."],["Cookies und Analytics","In der Basisversion sind keine Marketing- oder Analytics-Cookies integriert."],["Kontakt","Kontakt-E-Mail: tutka.peter@gmail.com"]]},
 pl:{back:"Wróć do tutka.sk",title:"Polityka prywatności",intro:"Ta strona zawiera podstawowe informacje o przetwarzaniu danych osobowych podczas kontaktu przez tutka.sk.",sections:[["Cel przetwarzania","Dane z zapytania są używane wyłącznie do komunikacji dotyczącej usługi, przygotowania wyceny i dalszej komunikacji biznesowej."],["Zakres danych","Może to obejmować imię i nazwisko, firmę, e-mail, telefon oraz dobrowolnie podany opis projektu."],["Formularz kontaktowy","Obecny formularz przygotowuje wiadomość w kliencie e-mail użytkownika. Strona nie zapisuje treści formularza w bazie danych."],["Cookies i analityka","W wersji podstawowej nie są zintegrowane marketingowe ani analityczne pliki cookies."],["Kontakt","E-mail kontaktowy: tutka.peter@gmail.com"]]},
 es:{back:"Volver a tutka.sk",title:"Política de privacidad",intro:"Esta página ofrece información básica sobre el tratamiento de datos personales al contactar a través de tutka.sk.",sections:[["Finalidad del tratamiento","Los datos enviados con una solicitud se utilizan únicamente para comunicarse sobre el servicio solicitado, preparar un presupuesto y continuar la comunicación comercial relacionada."],["Datos tratados","Pueden incluir nombre, empresa, e-mail, teléfono y la descripción del proyecto facilitada voluntariamente."],["Formulario de contacto","El formulario actual prepara un mensaje en el cliente de e-mail del usuario. El sitio web no almacena el contenido del formulario en una base de datos."],["Cookies y analítica","La versión básica no integra cookies de marketing ni analítica."],["Contacto","E-mail de contacto: tutka.peter@gmail.com"]]}
};

export default function PrivacyPage(){const {lang}=useLanguage();const t=legal[lang];return <main className="legal-page"><div className="legal-wrap"><a href="/" className="legal-back">← {t.back}</a><p className="legal-kicker">TUTKA • DATA &amp; APPS</p><h1>{t.title}</h1><p className="legal-intro">{t.intro}</p>{t.sections.map((s:any)=><section key={s[0]}><h2>{s[0]}</h2><p>{s[1]}</p></section>)}</div></main>}
